{
 "title": "Arch Gateway Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "# of Completed Requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_completed{envoy_cluster_name=~\"openai|api_server\"}",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "input sequence length (p50)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(input_sequence_length_bucket[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "output sequence length (p50)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(output_sequence_length_bucket[1h])) by(le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "time to first token (p50)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(time_to_first_token_bucket[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(request_latency_bucket[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time per Output Token (50p)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(time_per_output_token_bucket[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tokens per Second(50p)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(tokens_per_second_bucket[1h])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}