@prompt_endpoint = http://localhost:10000

### prompt gateway request
POST {{prompt_endpoint}}/v1/chat/completions HTTP/1.1
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "how is the weather in seattle for next 10 days"
    }
  ]
}

### prompt gateway request default target
POST {{prompt_endpoint}}/v1/chat/completions HTTP/1.1
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "hello"
    }
  ]
}


### prompt gateway request (streaming)
POST {{prompt_endpoint}}/v1/chat/completions HTTP/1.1
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "how is the weather in seattle for next 10 days"
    }
  ],
  "stream": true
}


### prompt gateway request param gathering
POST {{prompt_endpoint}}/v1/chat/completions HTTP/1.1
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "how is the weather in seattle"
    }
  ]
}

### prompt gateway request param gathering and function calling
POST {{prompt_endpoint}}/v1/chat/completions HTTP/1.1
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "how is the weather in seattle"
    },
    {
      "role": "assistant",
      "content": "It seems I'm missing some information. Could you provide the following details days ?",
      "model": "Arch-Function-1.5b"
    },
    {
      "role": "user",
      "content": "for next 10 days"
    }
  ]
}

### prompt gateway request param gathering and function calling (streaming)
POST {{prompt_endpoint}}/v1/chat/completions HTTP/1.1
Content-Type: application/json

{
  "model": "--",
  "messages": [
    {
      "role": "user",
      "content": "how is the weather in seattle"
    },
    {
      "role": "assistant",
      "content": "It seems I'm missing some information. Could you provide the following details days ?",
      "model": "Arch-Function-1.5b"
    },
    {
      "role": "user",
      "content": "for next 10 days"
    }
  ],
  "stream": true
}
