### talk to function calling endpoint
@model_server_endpoint = http://localhost:51000
@archfc_endpoint = https://api.fc.archgw.com
POST {{model_server_endpoint}}/function_calling HTTP/1.1
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "hi"
    },
    {
      "role": "assistant",
      "content": "Certainly! How can I assist you today"
    },
    {
        "role": "user",
        "content": "Get me weather for Seattle"
    },
    {
      "role": "assistant",
      "content": "Definitely. How many days of weather would you like to see?"
    },
    {
        "role": "user",
        "content": "5 days"
    },
    {
        "role": "tool",
        "content": "the weather is amazing."
    },
    {
        "role": "user",
        "content": "how about Austin"
    }
  ],
  "tools": [
    {
        "id": "weather-112",
        "type": "function",
        "function": {
            "name": "get_current_weather",
            "description": "Get current weather at a location.",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "str",
                        "description": "The location to get the weather for",
                        "format": "City, State"
                    },
                    "days": {
                        "type": "str",
                        "description": "the number of days for the request."
                    }
                },
                "required": ["location", "days"]
            }
        }
    }
  ]
}
### talk to Arch-Intent directly for completion
POST https://api.fc.archgw.com/v1/chat/completions HTTP/1.1
Content-Type: application/json

{
  "model": "Arch-Intent",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant.\n\nYou task is to check if there are any tools that can be used to help the last user message in conversations according to the available tools listed below.\n\n<tools>\n{\"index\": \"T0\", \"type\": \"function\", \"function\": {\"name\": \"weather_forecast\", \"parameters\": {\"type\": \"object\", \"properties\": {\"city\": {\"type\": \"str\"}, \"days\": {\"type\": \"int\"}}, \"required\": [\"city\", \"days\"]}}}\n</tools>\n\nProvide your tool assessment for ONLY THE LAST USER MESSAGE in the above conversation:\n- First line must read 'Yes' or 'No'.\n- If yes, a second line must include a comma-separated list of tool indexes.\n"
    },
    { "role": "user", "content": "hi" }
  ],
  "stream": false
}


### talk to Arch-Intent directly for completion


POST {{model_server_endpoint}}/function_calling HTTP/1.1
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "hi"
    },
    {
      "role": "assistant",
      "content": "Can you tell me your location and how many days you want?"
    },
    {
      "role": "user",
      "content": "Seattle"
    },
    {
        "role": "assistant",
        "content": "Can you please provide me the days for the weather forecast?"
    },
    {
        "role": "user",
        "content": "5 days"
    }
  ],
  "tools": [
    {
        "id": "weather-112",
        "type": "function",
        "function": {
            "name": "get_current_weather",
            "description": "Get current weather at a location.",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "str",
                        "description": "The location to get the weather for",
                        "format": "City, State"
                    },
                    "days": {
                        "type": "str",
                        "description": "the number of days for the request."
                    }
                },
                "required": ["location", "days"]
            }
        }
    }
  ]
}
### talk to Arch-Intent directly for completion
POST https://api.fc.archgw.com/v1/chat/completions HTTP/1.1
Content-Type: application/json

{
  "model": "Arch-Intent",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant.\n\nYou task is to check if there are any tools that can be used to help the last user message in conversations according to the available tools listed below.\n\n<tools>\n{\"index\": \"T0\", \"type\": \"function\", \"function\": {\"name\": \"weather_forecast\", \"parameters\": {\"type\": \"object\", \"properties\": {\"city\": {\"type\": \"str\"}, \"days\": {\"type\": \"int\"}}, \"required\": [\"city\", \"days\"]}}}\n</tools>\n\nProvide your tool assessment for ONLY THE LAST USER MESSAGE in the above conversation:\n- First line must read 'Yes' or 'No'.\n- If yes, a second line must include a comma-separated list of tool indexes.\n"
    },
    { "role": "user", "content": "what is your name" }
  ],
  "stream": false
}

### talk to Arch-Intent directly for completion

POST {{model_server_endpoint}}/function_calling HTTP/1.1
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "Give me a product recommendation"
    },
    {
      "role": "user",
      "content": "Sure, I can help with that. Could you please specify the category you're interested in, such as electronics, clothing, or books?"
    },
    {
      "role": "user",
      "content": "i would like phones"
    },
    {
      "role": "user",
      "content": "May I have your unique identifier and the maximum number of recommendations you want to receive?"
    },
    {
      "role": "user",
      "content": "user id is 1234 and 5 recommendations please"
    }
  ],
  "tools": [
    {
        "id": "weather-112",
        "type": "function",
        "function":
        {
            "name": "product_recommendation",
            "description": "Provide personalized product recommendations for users based on their preferences and purchase history.",
            "parameters": {
                "type": "object",
                "properties": {
                    "user_id": {
                        "type": "str",
                        "description": "Unique identifier for the user."
                    },
                    "category": {
                        "type": "str",
                        "description": "Product category for recommendations."
                    },
                    "max_results": {
                        "type": "int",
                        "description": "Maximum number of recommended products to retrieve.",
                        "default": 10
                    }
                },
                "required": ["user_id", "category"]
            }
        }

    }
  ]
}
### talk to Arch-Intent directly for completion
POST {{model_server_endpoint}}/function_calling HTTP/1.1
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "Give me a product recommendation"
    },
    {
      "role": "assistant",
      "content": "Can you please specify the category of products you are interested in?"
    },
    {
      "role": "user",
      "content": "Phones"
    }
  ],
  "tools": [
    {
        "id": "recommendation-112",
        "type": "function",
        "function":
        {
            "name": "product_recommendation",
            "description": "Provides product recommendations",
            "parameters": {
                "type": "object",
                "properties": {
                    "category": {
                        "type": "str",
                        "description": "Product category for recommendations",
                        "enum": ["electronics", "clothing", "books", "phones"]
                    },
                    "max_results": {
                        "type": "int",
                        "description": "Maximum number of recommended products to retrieve.",
                        "default": 10
                    }
                },
                "required": ["category"]
            }
        }

    }
  ]
}
### talk to Arch-Intent directly for completion
### talk to Arch-Intent directly for completion

POST {{model_server_endpoint}}/function_calling HTTP/1.1
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": " Can you show the workforce data for agency staff in 3 days"
    },
    {
      "role": "assistant",
      "content": "Of course, I can help with that. However, I need the region and staffing type to provide the workforce data. Could you please provide that information?"
    },
    {
      "role": "user",
      "content": "america"
    }
  ],
  "tools": [
    {
        "id": "hr-112",
        "type": "function",
        "function":
          {
        "name": "get_hr_data",
        "description": "Get workforce data like headcount and satisfacton levels by region and staffing type.",
        "parameters": {
            "type": "object",
            "properties": {
                "staffing_type": {
                    "type": "str",
                    "description": "Staffing type of employees"
                },
                "region": {
                    "type": "str",
                    "description": "Geographical region for which you want workforce data.",
                    "enum": ["americas", "emea", "apac"]
                },
                "point_in_time": {
                    "type": "str",
                    "description": "the point in time for which to retrieve data.",
                    "default": "1"
                }
            },
            "required": ["staffing_type", "region"]
        }
    }
    }
  ]
}

### talk to Arch-Intent directly for completion

POST {{model_server_endpoint}}/function_calling HTTP/1.1
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "Start a insurance policy with 500 deductible"
    }
  ],
  "tools": [
    {"type": "function",
     "function": {"name": "policy_qa",
      "description": "Handle general Q/A related to insurance.",
      "parameters": {"type": "object", "properties": {}, "required": []}}},

    {"type": "function",
     "function": {"name": "get_policy_coverage",
      "description": "Retrieve the coverage details for a given policy type (car, boat, house, motorcycle).",
      "parameters": {"type": "object",
       "properties": {"policy_type": {"type": "str",
         "description": "The type of policy."}},
       "required": ["policy_type"]}}},

    {"type": "function",
     "function": {"name": "initiate_policy",
      "description": "Start a policy coverage for car, boat, motorcycle or house.",
      "parameters": {"type": "object",
       "properties": {"policy_type": {"type": "str",
         "description": "The type of policy, option - car, boat, house, motorcycle."},
        "deductible": {"type": "float",
         "description": "The deductible amount set for the policy."}},
       "required": ["policy_type", "deductible"]}}},

    {"type": "function",
     "function": {"name": "update_claim",
      "description": "Update the notes on the claim.",
      "parameters": {"type": "object",
       "properties": {"claim_id": {"type": "str",
         "description": "The claim number."},
        "notes": {"type": "str",
         "description": "Notes about the claim number for your adjustor to see."}},
       "required": ["claim_id"]}}},

    {"type": "function",
     "function": {"name": "update_deductible",
      "description": "Update the deductible amount for a specific policy coverage.",
      "parameters": {"type": "object",
       "properties": {"policy_id": {"type": "str",
         "description": "The ID of the policy."},
        "deductible": {"type": "float",
         "description": "The deductible amount set for the policy."}},
       "required": ["policy_id", "deductible"]}}}
  ]
}
### talk to Arch-Intent directly for completion

POST {{model_server_endpoint}}/function_calling HTTP/1.1
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "Identify sales opportunities in South America for the retail industry"
    }
  ],
  "tools": [
    {
        "id": "weather-112",
        "type": "function",
        "function":
          {
    "name": "sales_opportunity",
    "description": "Retrieve potential sales opportunities based for a particular industry type in a region.",
    "parameters": {
        "type": "object",
        "properties": {
            "region": {
                "type": "str",
                "description": "Geographical region to identify sales opportunities."
            },
            "industry": {
                "type": "str",
                "description": "Industry type."
            },
            "max_results": {
                "type": "int",
                "description": "Maximum number of sales opportunities to retrieve.",
                "default": 20
            }
        },
        "required": ["region", "industry"]
    }
}

    }
  ]
}
