@model_server_endpoint = http://localhost:51000
@archfc_endpoint = https://api.fc.archgw.com

### single turn function calling all parameters insurance agent summary

POST {{model_server_endpoint}}/function_calling HTTP/1.1
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "Get me the summary for devices 123387, 10298437,and 129833 in the last 8 days"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "device_summary",
        "description": "Retrieve network statisitcs for specific devices within a time range",
        "parameters": {
          "type": "object",
          "properties": {
            "device_ids": {
              "type": "list",
              "description": "A list of device indentifiers (IDs) to retrieve statistics for"
            },
            "days": {
              "type": "int",
              "description": "the number of days for which to gather device statistics.",
              "default": 7
            }
          },
          "required": ["device_ids"]
        }
      }
    },
    {
      "type": "function",
      "function": {
        "name": "reboot_devices",
        "description": "Reboot a list of devices",
        "parameters": {
          "type": "object",
          "properties": {
            "device_ids": {
              "type": "list",
              "description": "A list of device indentifiers (IDs) to reboot"
            }
          }
        },
        "required": ["device_ids"]
      }
    }
  ]
}

### single turn function calling all parameters insurance agent reboot

POST {{model_server_endpoint}}/function_calling HTTP/1.1
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "reboot devices 123387, 10298437,and 129833"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "device_summary",
        "description": "Retrieve network statisitcs for specific devices within a time range",
        "parameters": {
          "type": "object",
          "properties": {
            "device_ids": {
              "type": "list",
              "description": "A list of device indentifiers (IDs) to retrieve statistics for"
            },
            "days": {
              "type": "int",
              "description": "the number of days for which to gather device statistics.",
              "default": 7
            }
          },
          "required": ["device_ids"]
        }
      }
    },
    {
      "type": "function",
      "function": {
        "name": "reboot_devices",
        "description": "Reboot a list of devices",
        "parameters": {
          "type": "object",
          "properties": {
            "device_ids": {
              "type": "list",
              "description": "A list of device indentifiers (IDs) to reboot"
            }
          }
        },
        "required": ["device_ids"]
      }
    }
  ]
}


### single turn function calling no parameters insurance agent summary

POST {{model_server_endpoint}}/function_calling HTTP/1.1
Content-Type: application/json


{
  "messages": [
    {
      "role": "user",
      "content": "Get me the summary for my devices"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "device_summary",
        "description": "Retrieve network statisitcs for specific devices within a time range",
        "parameters": {
          "type": "object",
          "properties": {
            "device_ids": {
              "type": "list",
              "description": "A list of device indentifiers (IDs) to retrieve statistics for"
            },
            "days": {
              "type": "int",
              "description": "the number of days for which to gather device statistics.",
              "default": 7
            }
          },
          "required": ["device_ids"]
        }
      }
    },
    {
      "type": "function",
      "function": {
        "name": "reboot_devices",
        "description": "Reboot a list of devices",
        "parameters": {
          "type": "object",
          "properties": {
            "device_ids": {
              "type": "list",
              "description": "A list of device indentifiers (IDs) to reboot"
            }
          }
        },
        "required": ["device_ids"]
      }
    }
  ]
}


### single turn function calling no parameters insurance agent reboot

POST {{model_server_endpoint}}/function_calling HTTP/1.1
Content-Type: application/json


{
  "messages": [
    {
      "role": "user",
      "content": "reboot my devices"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "device_summary",
        "description": "Retrieve network statisitcs for specific devices within a time range",
        "parameters": {
          "type": "object",
          "properties": {
            "device_ids": {
              "type": "list",
              "description": "A list of device indentifiers (IDs) to retrieve statistics for"
            },
            "days": {
              "type": "int",
              "description": "the number of days for which to gather device statistics.",
              "default": 7
            }
          },
          "required": ["device_ids"]
        }
      }
    },
    {
      "type": "function",
      "function": {
        "name": "reboot_devices",
        "description": "Reboot a list of devices",
        "parameters": {
          "type": "object",
          "properties": {
            "device_ids": {
              "type": "list",
              "description": "A list of device indentifiers (IDs) to reboot"
            }
          }
        },
        "required": ["device_ids"]
      }
    }
  ]
}

### multi turn single function calling all parameters insurance agent summary

POST {{model_server_endpoint}}/function_calling HTTP/1.1
Content-Type: application/json


{
  "messages": [
    {
      "role": "user",
      "content": "hi"
    },
    {
      "role": "assistant",
      "content": "Certainly! How can I assist you today"
    },
    {
      "role": "user",
      "content": "get me a summary for my devices"
    },
    {
      "role": "assistant",
      "content": "Definitely. what device ids would you like to see a summary for?"
    },
    {
      "role": "user",
      "content": "1231094, 1293818, and 1298023"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "device_summary",
        "description": "Retrieve network statisitcs for specific devices within a time range",
        "parameters": {
          "type": "object",
          "properties": {
            "device_ids": {
              "type": "list",
              "description": "A list of device indentifiers (IDs) to retrieve statistics for"
            },
            "days": {
              "type": "int",
              "description": "the number of days for which to gather device statistics.",
              "default": 7
            }
          },
          "required": ["device_ids"]
        }
      }
    },
    {
      "type": "function",
      "function": {
        "name": "reboot_devices",
        "description": "Reboot a list of devices",
        "parameters": {
          "type": "object",
          "properties": {
            "device_ids": {
              "type": "list",
              "description": "A list of device indentifiers (IDs) to reboot"
            }
          }
        },
        "required": ["device_ids"]
      }
    }
  ]
}


### multi turn single function calling all paramters insurance agent reboot

POST {{model_server_endpoint}}/function_calling HTTP/1.1
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "hi"
    },
    {
      "role": "assistant",
      "content": "Certainly! How can I assist you today"
    },
    {
      "role": "user",
      "content": "reboot my devices"
    },
    {
      "role": "assistant",
      "content": "Definitely. what device ids would you like to reboot?"
    },
    {
      "role": "user",
      "content": "1231094, 1293818, and 1298023"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "device_summary",
        "description": "Retrieve network statisitcs for specific devices within a time range",
        "parameters": {
          "type": "object",
          "properties": {
            "device_ids": {
              "type": "list",
              "description": "A list of device indentifiers (IDs) to retrieve statistics for"
            },
            "days": {
              "type": "int",
              "description": "the number of days for which to gather device statistics.",
              "default": 7
            }
          },
          "required": ["device_ids"]
        }
      }
    },
    {
      "type": "function",
      "function": {
        "name": "reboot_devices",
        "description": "Reboot a list of devices",
        "parameters": {
          "type": "object",
          "properties": {
            "device_ids": {
              "type": "list",
              "description": "A list of device indentifiers (IDs) to reboot"
            }
          }
        },
        "required": ["device_ids"]
      }
    }
  ]
}

### multi turn single function calling all parameters change of intent insurance agent summary

POST {{model_server_endpoint}}/function_calling HTTP/1.1
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "Can you show me the summary for my devices?"
    },
    {
      "role": "assistant",
      "content": "Sure! Can you provide the device IDs you would like a summary for?"
    },
    {
      "role": "user",
      "content": "Device IDs are 1231094 and 1293818."
    },
    {
      "role": "assistant",
      "content": "For how many days would you like to see the summary? If not specified, I’ll use the default of 7 days."
    },
    {
      "role": "user",
      "content": "Actually, use devices 1298023 and 1293819 instead, for 5 days."
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "device_summary",
        "description": "Retrieve network statisitcs for specific devices within a time range",
        "parameters": {
          "type": "object",
          "properties": {
            "device_ids": {
              "type": "list",
              "description": "A list of device indentifiers (IDs) to retrieve statistics for"
            },
            "days": {
              "type": "int",
              "description": "the number of days for which to gather device statistics.",
              "default": 7
            }
          },
          "required": ["device_ids"]
        }
      }
    },
    {
      "type": "function",
      "function": {
        "name": "reboot_devices",
        "description": "Reboot a list of devices",
        "parameters": {
          "type": "object",
          "properties": {
            "device_ids": {
              "type": "list",
              "description": "A list of device indentifiers (IDs) to reboot"
            }
          }
        },
        "required": ["device_ids"]
      }
    }
  ]
}
