{
 "title": "Arch Gateway Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "# of Completd Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_completed{envoy_cluster_name=~\"openai|api_server\"}",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Output Sequence Length 50th Percentile over last hour (tokens)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(output_sequence_length_bucket[1h])) by(le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Sequence Length 50th percentile over last hour (tokens)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(input_sequence_length_bucket[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 50th Percentile over last hour (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(latency_bucket[60m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(time_to_first_token_bucket[60m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Per Output Token 50th Percentile over last hour (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(time_per_output_token_bucket[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to First Token 50th percentile over last hour (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(time_to_first_token_bucket[1h])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}