POST http://localhost:4318/v1/traces
Content-Type: application/json

{
  "resourceSpans": [
    {
      "resource": {
        "attributes": [
          { "key": "service.name", "value": { "stringValue": "upstream-llm" } }
        ]
      },
      "scopeSpans": [
        {
          "scope": { "name": "default", "version": "1.0", "attributes": [] },
          "spans": [
            {
              "traceId": "fa8f7c410c28092faafbd7d4a2f5e742",
              "spanId": "4dc43055a07410d6",
              "parentSpanId": "f0acd74216a5e179",
              "name": "archgw",
              "startTimeUnixNano": "1731363782228270000",
              "endTimeUnixNano": "1731363787843156000",
              "kind": 1,
              "attributes": []
            }
          ]
        }
      ]
    }
  ]
}
