# coding: utf-8

"""
    OMF API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_embedding_response import CreateEmbeddingResponse

class TestCreateEmbeddingResponse(unittest.TestCase):
    """CreateEmbeddingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateEmbeddingResponse:
        """Test CreateEmbeddingResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateEmbeddingResponse`
        """
        model = CreateEmbeddingResponse()
        if include_optional:
            return CreateEmbeddingResponse(
                data = [
                    openapi_client.models.embedding.Embedding(
                        index = 56, 
                        embedding = [
                            1.337
                            ], 
                        object = 'embedding', )
                    ],
                model = '',
                object = 'list',
                usage = openapi_client.models.create_embedding_response_usage.CreateEmbeddingResponse_usage(
                    prompt_tokens = 56, 
                    total_tokens = 56, )
            )
        else:
            return CreateEmbeddingResponse(
                data = [
                    openapi_client.models.embedding.Embedding(
                        index = 56, 
                        embedding = [
                            1.337
                            ], 
                        object = 'embedding', )
                    ],
                model = '',
                object = 'list',
                usage = openapi_client.models.create_embedding_response_usage.CreateEmbeddingResponse_usage(
                    prompt_tokens = 56, 
                    total_tokens = 56, ),
        )
        """

    def testCreateEmbeddingResponse(self):
        """Test CreateEmbeddingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
