# coding: utf-8

"""
    OMF API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.embedding import Embedding

class TestEmbedding(unittest.TestCase):
    """Embedding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Embedding:
        """Test Embedding
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Embedding`
        """
        model = Embedding()
        if include_optional:
            return Embedding(
                index = 56,
                embedding = [
                    1.337
                    ],
                object = 'embedding'
            )
        else:
            return Embedding(
                index = 56,
                embedding = [
                    1.337
                    ],
                object = 'embedding',
        )
        """

    def testEmbedding(self):
        """Test Embedding"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
