# coding: utf-8

"""
    OMF API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.embeddings_api import EmbeddingsApi


class TestEmbeddingsApi(unittest.TestCase):
    """EmbeddingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmbeddingsApi()

    def tearDown(self) -> None:
        pass

    def test_create_embedding(self) -> None:
        """Test case for create_embedding

        Creates an embedding vector representing the input text.
        """
        pass


if __name__ == '__main__':
    unittest.main()
