{
 "title": "Arch Gateway Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "# of Completd Requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_completed{envoy_cluster_name=~\"openai|api_server\"}",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "input sequence length (p50)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(input_sequence_length_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "output sequence length (p50)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(output_sequence_length_bucket[5m])) by(le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "time to first token (p50)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(time_to_first_token_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(latency_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(time_to_first_token_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}