/**
 * OMF API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateEmbeddingResponseUsage } from './CreateEmbeddingResponseUsage';
import { Embedding } from './Embedding';
import { HttpFile } from '../http/http';

export class CreateEmbeddingResponse {
    /**
    * The list of embeddings generated by the model.
    */
    'data': Array<Embedding>;
    /**
    * The name of the model used to generate the embedding.
    */
    'model': string;
    /**
    * The object type, which is always \"list\".
    */
    'object': CreateEmbeddingResponseObjectEnum;
    'usage': CreateEmbeddingResponseUsage;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<Embedding>",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "CreateEmbeddingResponseObjectEnum",
            "format": ""
        },
        {
            "name": "usage",
            "baseName": "usage",
            "type": "CreateEmbeddingResponseUsage",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateEmbeddingResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum CreateEmbeddingResponseObjectEnum {
    List = 'list'
}

