/**
 * OMF API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The usage information for the request.
*/
export class CreateEmbeddingResponseUsage {
    /**
    * The number of tokens used by the prompt.
    */
    'promptTokens': number;
    /**
    * The total number of tokens used by the request.
    */
    'totalTokens': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "promptTokens",
            "baseName": "prompt_tokens",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalTokens",
            "baseName": "total_tokens",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateEmbeddingResponseUsage.attributeTypeMap;
    }

    public constructor() {
    }
}

