services:
  weather_forecast_service:
    build:
      context: ./
    environment:
      - OLTP_HOST=http://otel-collector:4317
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "18083:80"

  chatbot_ui:
    build:
      context: ../shared/chatbot_ui
    ports:
      - "18080:8080"
    environment:
      # this is only because we are running the sample app in the same docker container environment as archgw
      - CHAT_COMPLETION_ENDPOINT=http://host.docker.internal:10000/v1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./arch_config.yaml:/app/arch_config.yaml

  otel-collector:
    build:
      context: ../shared/honeycomb/
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ../shared/honeycomb/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    env_file:
      - .env
    environment:
      - HONEYCOMB_API_KEY

  prometheus:
    build:
      context: ../shared/prometheus

  grafana:
    build:
      context: ../shared/grafana
    ports:
      - "3000:3000"
