from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ManagedClusterClientConfig(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, url=None, ca_bundle=None):  # noqa: E501
        """ManagedClusterClientConfig - a model defined in OpenAPI

        :param url: The url of this ManagedClusterClientConfig.  # noqa: E501
        :type url: str
        :param ca_bundle: The ca_bundle of this ManagedClusterClientConfig.  # noqa: E501
        :type ca_bundle: str
        """
        self.openapi_types = {"url": str, "ca_bundle": str}

        self.attribute_map = {"url": "url", "ca_bundle": "caBundle"}

        self._url = url
        self._ca_bundle = ca_bundle

    @classmethod
    def from_dict(cls, dikt) -> "ManagedClusterClientConfig":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ManagedClusterClientConfig of this ManagedClusterClientConfig.  # noqa: E501
        :rtype: ManagedClusterClientConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this ManagedClusterClientConfig.


        :return: The url of this ManagedClusterClientConfig.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this ManagedClusterClientConfig.


        :param url: The url of this ManagedClusterClientConfig.
        :type url: str
        """

        self._url = url

    @property
    def ca_bundle(self) -> str:
        """Gets the ca_bundle of this ManagedClusterClientConfig.


        :return: The ca_bundle of this ManagedClusterClientConfig.
        :rtype: str
        """
        return self._ca_bundle

    @ca_bundle.setter
    def ca_bundle(self, ca_bundle: str):
        """Sets the ca_bundle of this ManagedClusterClientConfig.


        :param ca_bundle: The ca_bundle of this ManagedClusterClientConfig.
        :type ca_bundle: str
        """

        self._ca_bundle = ca_bundle
